backend:
  name: github
  repo: zivtech/chainalysis
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/docs-landing.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}

  - name: "docs"
    label: "Docs"
    folder: "src/pages/docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "docs"}
      - {label: "Path", name: "path", widget: "string", default: "/docs/", hint: "Add a relative path starting with \"/docs/\"."}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Keywords", name: "keywords", widget: "string", hint: "Enter a comma-separated list of keywords that are useful for search."}
      - {label: "Body", name: "body", widget: "markdown"}
